// GENERAL ACTION NAMES
export const CLEAR = 'CLEAR';
export const TOGGLE = 'TOGGLE';


// USER ACTIONS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const ADD_FRIEND = 'ADD_FRIEND';



// ERROR ACTIONS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// BUSINESS ACTIONS
export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_FAIL = 'REGISTER_BUSINESS_FAIL';
export const CLEAR_REGISTER_SUCCESS = 'CLEAR_REGISTER_SUCCESS';

export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS';
export const FETCH_BUSINESS_DETAILS_FAIL = 'FETCH_BUSINESS_DETAILS_FAIL';
export const FETCH_BUSINESS_DETAILS_SUCCESS = 'FETCH_BUSINESS_DETAILS_SUCCESS';

export const FETCH_MY_BUSINESSES = 'FETCH_MY_BUSINESSES';
export const FETCH_MY_BUSINESSES_FAIL = 'FETCH_MY_BUSINESSES_FAIL';
export const FETCH_MY_BUSINESSES_SUCCESS = 'FETCH_MY_BUSINESSES_SUCCESS';

export const GET_NEARBY_BUSINESSES = 'GET_NEARBY_BUSINESSES';
export const GET_NEARBY_BUSINESSES_FAIL = 'GET_NEARBY_BUSINESSES_FAIL';
export const GET_NEARBY_BUSINESSES_SUCCESS = 'GET_NEARBY_BUSINESSES_SUCCESS';

// THEME ACTIONS
export const SET_THEME = 'SET_THEME';


// NOTIFICATION ACTIONS
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const LOAD_NOTIFICATION = 'LOAD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// SOCKET ACTIONS
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';

// ACTIVE CHAT ACTIONS
export const FETCH_CHAT = 'FETCH_CHAT';
export const FETCH_CHAT_FAIL = 'FETCH_CHAT_FAIL';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const NEW_MESSAGE = 'NEW_MESSAGE';



