// USER ACTIONS => WILL BE REMOVED OR REBUILT IN THE FUTURE
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';

// USER AUTH ACTIONS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// ERROR ACTIONS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// BUSINESS ACTIONS
export const BUSINESS_LOADING = 'BUSINESS_LOADING';
export const BUSINESS_LOADED = 'BUSINESS_LOADED';
export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_FAIL = 'REGISTER_BUSINESS_FAIL';
export const CLEAR_REGISTER_SUCCESS = 'CLEAR_REGISTER_SUCCESS';

export const FETCH_BUSINESS_DETAILS_FAIL = 'FETCH_BUSINESS_DETAILS_FAIL';
export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS';
export const FETCH_BUSINESS_DETAILS_SUCCESS = 'FETCH_BUSINESS_DETAILS_SUCCESS';

export const FETCH_MY_BUSINESSES_FAIL = 'FETCH_MY_BUSINESSES_FAIL';
export const FETCH_MY_BUSINESSES = 'FETCH_MY_BUSINESSES';
export const FETCH_MY_BUSINESSES_SUCCESS = 'FETCH_MY_BUSINESSES_SUCCESS';
